### ISSUE TITLE
# Got Issues 

### ISSUE THREAD

**Issue by martinpk5** [AzizKpln/Moriarty-Project#26] opened 2021-04-22 06:26 UTC
Owner Name/Number Information:                              
                                                            
Traceback (most recent call last):                          
  File "/home/martin/Desktop/Hunter/Moriarty-Project/Moriarty.py", line 168, in <module>                                
    microsoft_mail(options.phone_number,options.microsoft_mail_address,options.mail_password)                           
  File "/home/martin/Desktop/Hunter/Moriarty-Project/Moriarty.py", line 62, in microsoft_mail                           
    WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div/form[1]/div/div/div[2]/div/div/div[1]/div[2]/div[2]/div/div/div/div[4]/div/div/div/div[2]/input"))).click()                                           
  File "/usr/lib/python3/dist-packages/selenium/webdriver/support/wait.py", line 86, in until                           
    raise TimeoutException(message, screen, stacktrace)     
selenium.common.exceptions.TimeoutException: Message:

**Comment by aniruddha2007** [comment] 2021-04-27 18:51
getting the same Issue, Running ParrotOS(bare metal)-latest build with Chromium 90.
Here's the CLI output
Traceback (most recent call last):
  File "/home/ani/Anonymous/Morarty/Moriarty-Project/Moriarty.py", line 168, in <module>
    microsoft_mail(options.phone_number,options.microsoft_mail_address,options.mail_password)
  File "/home/ani/Anonymous/Morarty/Moriarty-Project/Moriarty.py", line 62, in microsoft_mail
    WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div/form[1]/div/div/div[2]/div/div/div[1]/div[2]/div[2]/div/div/div/div[4]/div/div/div/div[2]/input"))).click()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/support/wait.py", line 86, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:



kinda looks like its having error connecting to outlook service? maybe.

**Comment by dropfr4me** [comment] 2021-04-29 05:21
Traceback (most recent call last):                                                                                                                                                                                                                                          
  File "/home/kali/Desktop/Moriarty-Project/Moriarty.py", line 168, in <module>                                                                                                                                                                                             
    microsoft_mail(options.phone_number,options.microsoft_mail_address,options.mail_password)                                                                                                                                                                               
  File "/home/kali/Desktop/Moriarty-Project/Moriarty.py", line 62, in microsoft_mail                                                                                                                                                                                        
    WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div/form[1]/div/div/div[2]/div/div/div[1]/div[2]/div[2]/div/div/div/div[4]/div/div/div/div[2]/input"))).click()                                                                       
  File "/usr/lib/python3/dist-packages/selenium/webdriver/support/wait.py", line 86, in until                                                                                                                                                                               
    raise TimeoutException(message, screen, stacktrace)                                                                                                                                                                                                                     
selenium.common.exceptions.TimeoutException: Message:        

getting the same

**Comment by LukeTeaKirk** [comment] 2021-04-29 19:14
Was an Xpath issue, fixed on my PR. Probably...

**Comment by dropfr4me** [comment] 2021-04-29 21:01
Awesome. thanks man

**Comment by AzizKpln** [comment] 2021-04-30 13:07
@LukeTeaKirk thank you for the pull request. I confirmed it. You guys can try to re-install the tool because the issue stems from xpath as @LukeTeaKirk  mentioned.

**Closed by AzizKpln** 2021-04-30 13:07 UTC
